// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmDFLzf2pA20q8G31qvlQ5LEowlgn0n5s',
    appId: '1:570019429913:web:269440b2234eddcb623488',
    messagingSenderId: '570019429913',
    projectId: 'rizqmart-486b8',
    authDomain: 'rizqmart-486b8.firebaseapp.com',
    storageBucket: 'rizqmart-486b8.firebasestorage.app',
    measurementId: 'G-7L6Y3YRF9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0AT2C41Rrd_nF1feRffyMWwCpHOgh7bI',
    appId: '1:570019429913:android:541a07ffbeeb5887623488',
    messagingSenderId: '570019429913',
    projectId: 'rizqmart-486b8',
    storageBucket: 'rizqmart-486b8.firebasestorage.app',
  );
}
